// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Video_Site.Entity;

public partial class DangKyKhoaHoc
{
    public string UserId { get; set; }

    public string MaKhoaHoc { get; set; }

    public DateTime? NgayDangKy { get; set; }

    public virtual KhoaHoc MaKhoaHocNavigation { get; set; }

    public virtual TaiKhoan User { get; set; }
}