// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using Microsoft.Data.SqlClient;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Data;
using System.Threading;
using System.Threading.Tasks;
using Video_Site.Entity;

namespace Video_Site.Entity
{
    public partial interface IVideo_SiteContextProcedures
    {
        Task<int> sp_DangKyTaiKhoanAsync(string userid, string username, string hoten, string email, string password, string role, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<sp_DangNhapResult>> sp_DangNhapAsync(string username, string password, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
    }
}
