// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Video_Site.Entity;

public partial class KhoaHoc
{
    public string MaKhoaHoc { get; set; }

    public string TenKhoaHoc { get; set; }

    public string MoTa { get; set; }

    public string Thumbnail { get; set; }

    public virtual ICollection<DangKyKhoaHoc> DangKyKhoaHocs { get; set; } = new List<DangKyKhoaHoc>();

    public virtual ICollection<VideoKhoaHoc> VideoKhoaHocs { get; set; } = new List<VideoKhoaHoc>();
}