// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Video_Site.Entity
{
    public partial class sp_DangNhapResult
    {
        [StringLength(20)]
        public string UserID { get; set; }
        [StringLength(25)]
        public string UserName { get; set; }
        [StringLength(255)]
        public string HoTen { get; set; }
        [StringLength(10)]
        public string Role { get; set; }
    }
}
