// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Video_Site.Entity;

public partial class VideoKhoaHoc
{
    public string MaVideo { get; set; }

    public string MaKhoaHoc { get; set; }

    public string TieuDe { get; set; }

    public string Link { get; set; }

    public virtual KhoaHoc MaKhoaHocNavigation { get; set; }
}