// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.SqlServer;

namespace Video_Site.Entity;

public partial class Video_SiteContext : DbContext
{
    public Video_SiteContext(DbContextOptions<Video_SiteContext> options)
        : base(options)
    {
    }

    public virtual DbSet<DangKyKhoaHoc> DangKyKhoaHocs { get; set; }

    public virtual DbSet<KhoaHoc> KhoaHocs { get; set; }

    public virtual DbSet<TaiKhoan> TaiKhoans { get; set; }

    public virtual DbSet<VideoKhoaHoc> VideoKhoaHocs { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<DangKyKhoaHoc>(entity =>
        {
            entity.HasKey(e => new { e.UserId, e.MaKhoaHoc }).HasName("PK__DangKyKh__8307C3557E93E62F");

            entity.ToTable("DangKyKhoaHoc");

            entity.Property(e => e.UserId)
                .HasMaxLength(20)
                .IsUnicode(false)
                .HasColumnName("UserID");
            entity.Property(e => e.MaKhoaHoc)
                .HasMaxLength(10)
                .IsUnicode(false);
            entity.Property(e => e.NgayDangKy)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime");

            entity.HasOne(d => d.MaKhoaHocNavigation).WithMany(p => p.DangKyKhoaHocs)
                .HasForeignKey(d => d.MaKhoaHoc)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__DangKyKho__MaKho__628FA481");

            entity.HasOne(d => d.User).WithMany(p => p.DangKyKhoaHocs)
                .HasForeignKey(d => d.UserId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__DangKyKho__UserI__619B8048");
        });

        modelBuilder.Entity<KhoaHoc>(entity =>
        {
            entity.HasKey(e => e.MaKhoaHoc);

            entity.ToTable("KhoaHoc");

            entity.Property(e => e.MaKhoaHoc)
                .HasMaxLength(10)
                .IsUnicode(false);
            entity.Property(e => e.TenKhoaHoc).HasMaxLength(50);
        });

        modelBuilder.Entity<TaiKhoan>(entity =>
        {
            entity.HasKey(e => e.UserId);

            entity.ToTable("TaiKhoan");

            entity.Property(e => e.UserId)
                .HasMaxLength(20)
                .IsUnicode(false)
                .HasColumnName("UserID");
            entity.Property(e => e.Email).HasMaxLength(50);
            entity.Property(e => e.HoTen).HasMaxLength(255);
            entity.Property(e => e.Password)
                .HasMaxLength(255)
                .IsUnicode(false);
            entity.Property(e => e.Role)
                .HasMaxLength(10)
                .IsUnicode(false);
            entity.Property(e => e.UserName)
                .HasMaxLength(25)
                .IsUnicode(false);
        });

        modelBuilder.Entity<VideoKhoaHoc>(entity =>
        {
            entity.HasKey(e => e.MaVideo);

            entity.ToTable("VideoKhoaHoc");

            entity.Property(e => e.MaVideo)
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.MaKhoaHoc)
                .HasMaxLength(10)
                .IsUnicode(false);
            entity.Property(e => e.TieuDe).HasMaxLength(50);

            entity.HasOne(d => d.MaKhoaHocNavigation).WithMany(p => p.VideoKhoaHocs)
                .HasForeignKey(d => d.MaKhoaHoc)
                .HasConstraintName("FK_VideoKhoaHoc_KhoaHoc");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}